### ISSUE TITLE
Weird error with closure functions

### ISSUE THREAD

**Issue by santiagobadia** [gridap/Gridap.jl#114]
I have this weird error, if I define a closure function `ufun` as below, the last line in the snippet, e.g., the creation of the `TrialFESpace` fails. If I delete `l` from the `ufun` expression, everything works.

What the heck is going on? 

Any suggestion?

```
using Gridap, Test

n = 2
model = CartesianDiscreteModel(partition=(n,))
diritag = [1]
order = 2
fespace = H1ConformingFESpace(Float64,model,order,diritag)

l = 1.0
ufun(x) = x[1]*(x[1]-2.0*l)
ufun_grad(x) = VectorValue(2*x[1]-2.0,)
bfun(x) = -2.0
∇(::typeof(ufun)) = ufun_grad

V = TestFESpace(fespace)
U = TrialFESpace(fespace,ufun)
```

**Comment by fverdugo** [comment]
use
```julia
const l = 1.0
```
I think this is associated with the fact that we use `Base._return_type`. I have found an alternative to do it better

**Comment by santiagobadia** [comment]
OK, the thing is that I had this problem in the code with Eric in which l is a result of a computation... I will think about a workaround. But let us see if we can fix this problem. I remember to have this problem before now that you mention it.

**Comment by fverdugo** [comment]
I think, you can define as constant the result of an operation. If not, try to annotate `l` with the wanted type in the function ufun.

```julia
function ufun(x)
   _l::Float64 = l
  x[1]*(x[1]-2.0*_l)
end
```
I am aware of this problem since quite long. With the new version of the low level abstractions that I am working on, it will not happen.

In any case, it is not very efficient to capture a global variable in a closure. This is one of the performance warnings in the manual of julia. They also say how to fix it.
