### ISSUE TITLE
A more efficient way to convert from coo to csc?

### ISSUE THREAD

**Issue by fverdugo** [gridap/Gridap.jl#181]
Currently, we have implemented the methods `sparse_from_coo` using the `sparse` function. 

However, I have realized that function `sparse` allocates an enormous amount of memory for a very short time. 

This is the major bottleneck in the code for a Poisson problem (if you use a decent solver like CG+AMG). In my laptop, I cannot solve beyond 3M cells because  this problem.

By looking into the `SparseArrays` docs, I have found the `sparse!` function, which allows some optimizations.

@victorsndvg can you take a look to the `sparse!` function to see if we can save a little bit of memory with it?

**Comment by fverdugo** [comment]
Just for reference. This is the code I use to solve large Poisson problems:

https://github.com/fverdugo/Poisson.jl

```jl
using Poisson
poisson(3) # warm-up
poisson(145) # 145^3 = 3048625 cells (largest problem I can solve in my laptop i7 16Gb)
```
It takes about 45 seconds to solve the 3M cell problem. Pas mal! but we will improve it.

If you want to profile the code:
```julia
using Poisson
using Profile
using ProfileView
@profview poisson(3) # warm-up
@profview poisson(100)
```

**Comment by victorsndvg** [comment]
I was diving into the SparseMatrix code to get a better understanding in order to compare `sparse` and `sparse!` functions.

As far as I understood, there is no too much difference among both functions. `sparse` function is in charge of creating and preallocating some arrays before calling to `sparse!`. `sparse!` function implements the algorithms to traverse the input arrays and generate the CSC sparse matrix.

You can see some of these allocations performed from the `sparse` function here:
https://github.com/JuliaLang/julia/blob/2d5741174ce3e6a394010d2e470e4269ca54607f/stdlib/SparseArrays/src/sparsematrix.jl#L646-658

Direct calls to `sparse!` also requires to preallocate these input arrays. You can see some `sparse!` function signatures in the following links:

  - https://github.com/JuliaLang/julia/blob/2d5741174ce3e6a394010d2e470e4269ca54607f/stdlib/SparseArrays/src/sparsematrix.jl#L717
  - https://github.com/JuliaLang/julia/blob/2d5741174ce3e6a394010d2e470e4269ca54607f/stdlib/SparseArrays/src/sparsematrix.jl#L825
  - https://github.com/JuliaLang/julia/blob/2d5741174ce3e6a394010d2e470e4269ca54607f/stdlib/SparseArrays/src/sparsematrix.jl#L833

Probably we could save some memory if we can reuse some of these input arrays ... but I don't know if this fits in our code. 

What do you think? any idea?

**Comment by fverdugo** [comment]
Hi @victorsndvg 

The version of `sparse!` in 

https://github.com/JuliaLang/julia/blob/2d5741174ce3e6a394010d2e470e4269ca54607f/stdlib/SparseArrays/src/sparsematrix.jl#L717

allows to re-use the coo-vectors `I,J,V` for the storage of the matrix (vectors `csccolptr, cscrowval, cscnzval`). 

The only drawback I see is that the vectors `I,J,V` are longer than `csccolptr, cscrowval, cscnzval`, and thus they need to be resized to save some memory. It seems that  `cscrowval, cscnzval` are resized, but not `csccolptr`, see: https://github.com/JuliaLang/julia/blob/2d5741174ce3e6a394010d2e470e4269ca54607f/stdlib/SparseArrays/src/sparsematrix.jl#L807

Thus, once the sparse matrix is created one keeps maintaining some memory (in vector `csccolptr`) that is not needed, but I don't think this is very problematic (at the end this will be a vector of  `Int32`). I prefer to have this extra memory than to have simultaneously in memory all vectors `I,J,V,csccolptr, cscrowval, cscnzval` that is what we have now...

Can you try to use `sparse!` and open a PR? Then, I will check if this allows me to solve a bigger problem in my computer.

Thanks!

**Comment by victorsndvg** [comment]
@fverdugo 

I already check what you are saying, but following the code I cannot understand why using `sparse!` funcion in our tests i get OutOfMemory errors ...

Anyway, I've checked the Poisson example, assuming we are using `sparse_from_coo` function in background, and it worked. I've partially done the changes (only for SparseMatrixCSC) in `update/sparse_from_coo` branch.

let me know if it works for you

**Comment by victorsndvg** [comment]
Branch referenced in previous commit is not working with julia 1.0 ...

**Comment by fverdugo** [comment]
The error in julia 1.0 is alarming. Perhaps the safest approach is to continue using `sparse`.
I close the issue.
