### ISSUE TITLE
Upwinded DG

### ISSUE THREAD

**Issue by santiagobadia** [gridap/Gridap.jl#307]
In order to implement DG methods, we need to compute 
```
(u^-u^-)*v^+ = (u+*n+ + u-*n-)*(v^+*n^+) = jump(u)*v^+*n^+
```
We can implement this term as
```
v^+*n^+ = 1/2( jump(v)) + mean(v)*n^+ 
```
So I think we have what we need.

But probably, we want to define other jump and mean operators, that allow us to consider different weights, etc, e.g., for interface problems in which these operators have weights that depend on the physical parameters. For efficiency issues, it would be nice to be able to extract `v^+*n^+` (the upwinded jump).

**Comment by fverdugo** [comment]
More than defining new jumps and mean operators, I would prefer (since it is provably more general) to allow more flexibility when operating with quantities on the skeleton (specially for multi-field, but also for single-field). 

With higher flexibility, the user would be able to implement more complex jump/mean operations according the particular needs. Something in the spirit I have done here:

https://github.com/gridap/GridapEmbedded.jl/blob/717982a18dfb73e1e8d12871502ecf7b589cd352/test/GridapEmbeddedTests/BimaterialPoissonCutFEMTests.jl#L91

We have already suffer from the lack of flexibility at the skeleton in the FSI tutorial:

https://github.com/gridap/Tutorials/blob/3e01a2cc4c65d8574599c68539d38efe9ea52951/src/fsi_tutorial.jl#L264

I know what is the problem and how to solve it, but it requires some work...

**Comment by fverdugo** [comment]
Implement this in 

https://github.com/gridap/Gridap.jl/blob/master/src/FESpaces/CellBases.jl

```julia
function Base.getproperty(x::SkeletonCellBasis, sym::Symbol)
  if sym == :inward
    ReducedSkeletonCellBasis(a.trial_style,1.0*a.left,0.0*a.right)
  elseif sym == :outward
    ReducedSkeletonCellBasis(a.trial_style,0.0*a.left,1.0*a.right)
  else
    getfield(x, sym)
  end
end

ReducedSkeletonCellBasis(l,r) = ReducedSkeletonCellBasis(l.trial_style,l,r)

```

Then in the driver you have two options (the second one is perhaps more performant):

```julia

a1 = 0.25
a2= 0.75

function jump_u(u)
  a1*u.inward + a2*u.outward
end

function jump_u(u)
 ReducedSkeletonCellBasis(a1*a.left,a2*a.right)
end

```

**Comment by fverdugo** [comment]
Fixed in PR #317. The chosen syntax for implementing user defined jumps is:
```julia
function jump_u(u)
  a1*u.inward - a2*u.outward
end
```

**Comment by fverdugo** [comment]
@santiagobadia I have been thinking is some alisases for `inward` and `outward`. We  could use
```julia
function jump_u(u)
  a1*u.⁺ - a2*u.⁻
end
```
which I find very nice.

 So we can have two variants:  a fancy one using unicode with `⁺` (`\^+`) and `⁻` (`\^-`) , and a less fancy one (but more portable) using ASCII with `inward` and `outward`.

BTW,  `⁺` -> `inward` or the other way arround?

**Comment by fverdugo** [comment]
These are not yet implemented. If you like them, we can implement these aliases in 1 second.
