### ISSUE TITLE
Applying Gridap to solving problems in solid mechanics

### ISSUE THREAD

**Issue by bhaveshshrimali** [gridap/Gridap.jl#318]
Hi @santiagobadia @fverdugo ,

Firstly, thank you for bringing `Gridap` to fruition. I am looking forward to pick it up soon.  :) I am particularly targetting applications involving PDEs (and later on coupled- PDE-ODEs) with periodic boundary conditions. These occur frequently in numerical homogenization of elliptic operators. 

I have a couple of questions: 

   * What would be the best place to start looking at in order to implement periodic boundary conditions? Is there a long term plan to use Gridap to solve such problems?

   *  For more general conditions to impose periodicity, such as in solid mechanics software (e.g. Abaqus), we write multi-point constraints to couple degrees of freedom on opposite facets using linear constraints. I guess this would involve tweaking the assembled tensors, or changing the assembly procedure. Is there a plan to support custom assemblers for problems?

I would also be happy to contribute tutorials once I make some progress on it.

Thanks again

**Comment by santiagobadia** [comment]
Hi @bhaveshshrimali 

We have big plans for Gridap in computational solid mechanics. You have probably checked the solid mechanics [tutorials](https://gridap.github.io/Tutorials/dev/). We have one example with state-depedent variables, in order to check that our machinery works for these problems. And we would like to explore a `GridapFE2` module, re-implement here our octree-based additive manufacturing [solvers](https://scholar.google.com/citations?user=B15AoQoAAAAJ&hl=en), etc. It would be nice to have more people involved, and even better application-experts collaborators.

Gridap already supports periodic boundary conditions. See this MHD [driver](https://github.com/gridapapps/GridapMHD.jl/blob/d43f3f809f0afb04ad3b728019749e36a2de4e0a/src/Hunt.jl#L30). It is as simple as
```
model = CartesianDiscreteModel(domain,partition; isperiodic=(false,false,true))
``` 
where `(false,false,true)` means periodic in `X` and `Y` direction and not in `Z`, as you can guess.

We already have the concept of (multi-dof) linear constraints, you can create a `FESpaceWithLinearConstraints` providing these constraints in a particular way. The Gridap assembler can deal with them. We plan to use this soon for h-adaptivity in finite elements. But I think that with the previous method you don't need to go that deep.

Thanks for the interest.

**Comment by fverdugo** [comment]
@bhaveshshrimali 

Here you have a minimal working example with periodic BCs (Poisson Eq.)

```julia
using Gridap

u(x) = sin(2*pi*(x[1]-0.25))*x[2]
f(x) = -Δ(u)(x)

domain = (0,1,0,2)
cells = (10,20)
model = CartesianDiscreteModel(domain,cells;isperiodic=(true,false))

labels = get_face_labeling(model)
add_tag_from_tags!(labels,"dirichlet",[1,2,3,4,5,6])

order = 2
V = TestFESpace(
 reffe=:Lagrangian, order=order, valuetype=Float64,
 conformity=:H1, model=model, dirichlet_tags="dirichlet")

U = TrialFESpace(V,u)

trian = Triangulation(model)
quad = CellQuadrature(trian,2*order)

a(u,v) = ∇(v)⋅∇(u)
l(v) = v*f
t_Ω = AffineFETerm(a,l,trian,quad)

op = AffineFEOperator(U,V,t_Ω)
uh = solve(op)

writevtk(trian,"pcbs",order=order,cellfields=["uh"=>uh])

```

![pbcs](https://user-images.githubusercontent.com/48508177/87242734-9923f900-c42f-11ea-8437-dcea5352f3ae.png)

Hope it helps.

**Comment by bhaveshshrimali** [comment]
Thanks very much to both of you.
 
> You have probably checked the solid mechanics tutorials. We have one example with state-depedent variables, in order to check that our machinery works for these problems.


Thanks @santiagobadia . I started with the Hyperelasticity example and the [damage example] (https://gridap.github.io/Tutorials/stable/pages/t010_isotropic_damage/) is my next on my list. 

> Here you have a minimal working example with periodic BCs (Poisson Eq.)


Thanks @fverdugo This is perfect


Appreciate both your responses. Will keep up with the latest developments on this. Thanks again!

**Comment by avigliotti** [comment]
if you guys have interest in solid mechanics you might also want to give a look at this

https://github.com/avigliotti/AD4SM.jl

it uses automatic differentiation to state and solve solid mechanics problems, solution is found as the minima of free energy, with residual forces being the gradient and tangent stiffness matrix the hessian of structure's strain energy, respectively.

p.s. didn't mean to steal focus from Gridap.jl, just share some work

**Comment by santiagobadia** [comment]
Thanks @avigliotti for sharing thsi info. 

We have been able to compute jacobians out of residuals and also jacobians and residuals out of energy functionals using `ForwardDiff` dual-number bassed AD engine. But for much simpler models as the ones you have considered. 

Hopefully, we will create tutorials with these capabilities soon.

**Comment by avigliotti** [comment]
The implementation of automatic differentiation in `AD4SM` is also based on `ForwardDiff`, which is a terrific and elegant package, the difference is that in `AD4SM` the Hessian is not evaluated recursively as the gradient of the gradient's components, but it is treated explicitly to take advantage of Hessian's symmetry, this way we only compute the upper half of it

**Comment by santiagobadia** [comment]
Thanks for all your comments.

I will close the issue, but feel free to open it again or create another one if needed.
