### ISSUE TITLE
joss paper: OSI approved software license?

### ISSUE THREAD

**Issue by TeroFrondelius** [gridap/Gridap.jl#342]
Hi,
I really like your idea to add Citing Gridap and Contributing to Gridap titles to the LICENSE.md file. However, I have to compare the text here: https://opensource.org/licenses/MIT and it's not matching. I think this might be the reason why Github is not automatically recognized your license to be MIT. I hope you can find a solution to keep the extra stuff in because I really see the benefit. Maybe you can link some discussion or something that states this is ok. Of course, the dull option is to remove the extra stuff and keep only the original MIT license text. 

X-ref: https://github.com/openjournals/joss-reviews/issues/2520

**Comment by santiagobadia** [comment]
After some research, it seems there is no way for GitHub to automatically detect an _enriched_ license file. The only two possibilities are: 1) to remove the citation, certificate of origin, etc, and keep the plain MIT license or 2) to keep it without the Github detection.

We would like to keep it as it is, if possible, since we have not modified a line of the MIT license and I consider that our license fulfills the requirements of JOSS. In fact, it is very common to find respected open source Github projects, e.g., Julia itself, DifferentialEquations.jl, deal.ii, etc, that are in the same situation as Gridap (no Github license detection).

**Comment by TeroFrondelius** [comment]
I come from a corporate background and the legal department can be a big pain in the ass. Thus, I want you to avoid a similar situation than this famous JSLint case https://www.youtube.com/watch?v=-hCimLnIsDA

**Comment by santiagobadia** [comment]
Ok, we have now put a plain MIT license, which is detected by Github. I close the issue.
