### ISSUE TITLE
joss paper: list of references

### ISSUE THREAD

**Issue by TeroFrondelius** [gridap/Gridap.jl#348]
Currently, you don't have any general FEM or algorithms citations, also the number of citations seems a bit too low for me. Could you add some references here: 

> The library provides a feature-rich set of discretization
techniques, including continuous and discontinuous FE methods with Lagrangian, RaviartThomas, or Nédélec interpolations

Also here, if you have a good reference(s):

>  Gridap adopts a novel software design that allows one to manipulate different types
of data associated with the cells of the computational mesh in a convenient way

And here:

> cells of the mesh are usually lazy, 

Xref: https://github.com/openjournals/joss-reviews/issues/2520

**Comment by santiagobadia** [comment]
We have added a reference with respect to the finite element abstractions. 

We do not have references for the other two sentences, but right after these sentences we explain what do they mean.  The software design is new, it is the first paper about Gridap, and since JOSS articles are not full-length articles, we cannot explain them with more detail here.

**Comment by TeroFrondelius** [comment]
Still, the total number of References seems low to me, comparing this is a fully-featured FEM package. Nevertheless, it's impossible to add a lot of references to a short text.
