### ISSUE TITLE
joss paper: memory benchmark

### ISSUE THREAD

**Issue by TeroFrondelius** [gridap/Gridap.jl#353]
In the paper, you have this statement: 
>  Instead, the value for a specific cell is computed on-the-fly when needed, which certainly reduces memory requirements. 

It would be really cool to benchmark this. We have had in JuliaFEM this benchmark case ([here is the paper](https://rakenteidenmekaniikka.journal.fi/article/view/64224/26397)): 
![image](https://user-images.githubusercontent.com/12501534/89879688-f98f8d00-dbcb-11ea-9fb1-96a60dea87e4.png)

Unfortunately, we don't mention memory usage, probably because it's huge, but I guess we should run both models on the same computer anyway. What do you think? 

Ping @KristofferC and @ahojukka5

Xref: https://github.com/openjournals/joss-reviews/issues/2520

**Comment by santiagobadia** [comment]
Due to the fact that the paper must be very short, we would like to skip performance analyses here. As stated in the JOSS rules, a performance analysis is only needed to support a performance claims in the article. **If you consider that this is a performance claim, we can eliminate it.** In any case, the statement is true, since the storage of the cell-wise element matrices replicates the entries related to degrees of freedom on the skeleton of the mesh.

The memory efficiency of `Gridap`, and even more important, its time-to-solution, compared to other software packages like deal.ii, Fenics, or JuliaFEM is very interesting, and we would like to evaluate this in the near future. But it is out of the scope of this article. So, I would not relate the performance analysis with the current JOSS paper.

**Comment by TeroFrondelius** [comment]
Naturally, my motivation is to get the benchmark in the paper, to get a citation to JuliaFEM paper.

**Comment by santiagobadia** [comment]
Now we have added a citation to your paper. 

As commented above, we are not making performance claims against your software or any other of the software projects we have cited, so we are not going to include performance analyses.

Please, make a decision based on this, and inform the editor @Kevin-Mattheus-Moerman about your final decision.

**Comment by TeroFrondelius** [comment]
Thanks. I close this issue because it's joss paper related. We will need to open new issues both in Gridap and JuliaFEM repos or discourse topic about FEM benchmarking. Maybe the benchmark could be a separate repo, where everyone could upload their model/results. Could we even run the benchmark on Travis CI or similar?
