### ISSUE TITLE
Implementation Issue: Linear Elastic on a single square element

### ISSUE THREAD

**Issue by Omega-xyZac** [gridap/Gridap.jl#355]
Hi guys,
I would appreciate any tips that you can give with the following issue. I am trying to implement a very simple linear elastic problem. In the problem we have a single square element (so that the FEM could be done analytically with ease). The structure on paper is 
```
4---3  --> F
|   |
1---2  --> F
```
Point 1 is fixed in the x-direction and point 4 is fixed in the x and y directions. Point 2 and 3 have a force of 1 in their x-direction's.

Here is an attempt:
```
using Gridap
using Gridap.FESpaces
using Gridap.Fields
using Gridap.ReferenceFEs
using Gridap.Geometry

domain = (0.0, 1.0, 0.0, 1.0);
model = CartesianDiscreteModel(domain,(1,1));

nodes_coords = get_node_coordinates(model);
#model.grid_topology.vertex_coordinates

labels = get_face_labeling(model);
add_tag_from_tags!(labels,"point1",[1,]);
add_tag_from_tags!(labels,"point4",[3,]);

#writevtk(model,string(pwd(),"\\Gridap LE Square Element\\square"))

function f(x)
    if x[1]==1
        return VectorValue(1,0);
    else
        return VectorValue(0,0);
    end
end

V0 = TestFESpace(
  reffe=:Lagrangian, order=1, valuetype=VectorValue{2,Float64},
  conformity=:H1, model=model, dirichlet_tags=["point1","point4"],
  dirichlet_masks=[(true,false),(true,true)])

g1(x) = VectorValue(0.0, 0.0)
g2(x) = VectorValue(0.0, 0.0)

U = TrialFESpace(V0,[g1,g2])

a(u,v) = ε(v) ⊙ σ(ε(u)) - v*f; # `-` doesn't make sense here, v*f should be in l(u)

using LinearAlgebra: tr
const E = 1;
const ν = 0.3;
const λ = (E*ν)/((1+ν)*(1-2*ν));
const μ = E/(2*(1+ν));
@law σ(ε) = λ*tr(ε)*one(ε) + 2*μ*ε;

trian = Triangulation(model)
degree = 2;
quad = CellQuadrature(trian,degree)
t_Ω = LinearFETerm(a,trian,quad)
op = AffineFEOperator(U,V0,t_Ω)
uh = solve(op)
```
The first issue is the definition of the bilinear form a( . , . ). This problem is posed in the weak form as: find u\in... such that a(u,v)=l(v) for all v. I haven't really seen any way to implement anything but a(u,v)=0 in gridap (as per the tutorials). The second issue is how to actually enforce the forces on nodes. Is something along the lines of what I have done appropriate? I understand that I could do this in a similar way to the L.E. tutorial but I would really like to implement this as per the explanation at the top.

**Comment by santiagobadia** [comment]
With regard to the bilinear form, I think that all you need is in this tutorial

https://gridap.github.io/Tutorials/dev/pages/t002_validation/

you can see a non-zero forcing term there:

```
a(u,v) = ∇(v)⊙∇(u)
b(v) = v*f

t_Ω = AffineFETerm(a,b,trian,quad)
```

With regard to point loads, the answer is not so short, and somehow related to the one about point-wise evaluations of FE functions. 

A point load can be mathematically represented as a distribution, e.g., a Dirac delta. What you propose, checking if the `x` is equal to a particular value does not work for different reasons (rounding errors for general coordinates) and more important, you cannot use Gauss quadratures and numerical integration (what we usually do in FEM) to compute the integral of f*v in that case, it does not have sense.

I would try first a distributed load that is smooth (e.g., constant). In that case, following the tutorials, you will see how to integrate this (Neumann) bc'on, e.g., here

https://gridap.github.io/Tutorials/dev/pages/t001_poisson/#Tutorial-1:-Poisson-equation-1

In a dirty way, you could do hacks if you know the node in which you want to put the force, but I don't like it much. 

Instead, e.g., I would consider a constructor for `f = DiracDelta(x_0)` that returns a `Distribution <: Field` that we know cannot be used with integration BUT instead, `integrate(f*v,trian,quad)` returns v(x). 

By the way, this problem is mathematically ill-posed (Dirac deltas are not in $H^{-1}$), but I know that for a fixed mesh it is not that important... and I agree we should provide this evil artifacts in Gridap.

**Comment by Omega-xyZac** [comment]
Thank you for the great reply, really appreciate the in-depth response.

**Comment by bricearnold** [comment]
@zjwegert Thank you very much for your reply. I tried but i didnt get something. Can you send me your skript?

**Comment by bricearnold** [comment]
@zjwegert Please can you help me? Since two weeks i always dont have the correct solution

**Comment by zjwegert** [comment]
Hi @bricearnold, sorry I'd completely forgotten to look at this for you. The code below should be something along the lines of what you need. I can't test at the moment but hopefully it puts you on the right track :).
**Define material values:**
```
E = 1.; ν = 0.3;
λ = E*ν/((1+ν)*(1-ν)); μ = E/(2*(1+ν));
C = E/(1-ν^2)*TensorValue([1 ν 0
			   ν 1 0
			   0 0 (1-ν)/2]);
```
**Define domain:**
```
nely,nelx = 2,2
domain = (0.0, nelx, 0.0, nely);
model = CartesianDiscreteModel(domain,(nelx,nely));
labels = get_face_labeling(model)
add_tag_from_tags!(labels,"l_support",[1,3,7]); # Support on left boundary + points
add_tag_from_tags!(labels,"r_stress",[2,4,8]); # Support on left boundary + points
```
**Define spaces:**
```
reffe = ReferenceFE(lagrangian,VectorValue{2,Float64},1)
V = TestFESpace(model, reffe, conformity=:H1,dirichlet_tags=["l_support"],
 dirichlet_masks=[(true,true)]);
U = TrialFESpace(V,[VectorValue(0.0, 0.0)])
```
**Define triangulation and measure:**
```
trian = Triangulation(model)
degree = 2
dΩ = Measure(trian,degree)
```
**Define weak form:**
```
# Bi-linear form
function a(u,v)
  return ∫(C ⊙ ε(u) ⊙ ε(v))dΩ
end
# Linear form/s
ltrian = BoundaryTriangulation(model, tags=)
dΓ = Measure(ltrian,degree)
n = get_normal_vector(ltrian)
function l_ΓN(VQ)
     v, q = VQ
     return ∫(v⋅n)*1 dΓ
end
```
**Form operator and solve:**
```
op = AffineFEOperator(a,l_ΓN,U,V)
uh = solve(op)
```

**Comment by bricearnold** [comment]
@zjwegert i thank you very very much
