### ISSUE TITLE
Adding x86 architecture to GH actions causes two tests to fail

### ISSUE THREAD

**Issue by amartinhuertas** [gridap/Gridap.jl#453]
More details here:

https://github.com/gridap/Gridap.jl/runs/1405739573?check_suite_focus=true#step:6:126

**Comment by fverdugo** [comment]
It seems that the json parser has read some integers as Int64 even in x86.

Try to replace 
https://github.com/gridap/Gridap.jl/blob/23f56ed660bf7b27331dfc2734a74905ffd96dd1/src/ReferenceFEs/CLagrangianRefFEs.jl#L157
by
```julia
extrusion = map(Int,Tuple(dict[:extrusion]))
```
A more elegant way of fixing this would be to configure the json parser to return `Int` instead of `Int64`. (Don't know if it is possible)

**Comment by amartinhuertas** [comment]
> Don't know if it is possible

Yes, it is possible!  Solved in PR: https://github.com/gridap/Gridap.jl/pull/456
