### ISSUE TITLE
delta-function derivatives

### ISSUE THREAD

**Issue by stevengj** [gridap/Gridap.jl#489]
PR #485 added delta functions (on points/lines/surfaces in the grid).

As noted in #408, many applications also use delta function derivatives ("dipoles", "quadrupoles", etcetera), which are simply functionals `δ′{v}` that evaluate derivatives of the test function `v` (integrating the derivative along a line or surface in the case of line/surface delta functions).

For example,
```jl
δ_point = DiracDelta{0}(model,tags=["mypoint1","mypoint2"])
δ_point′ = ∇⊙δ_point
```
would be a functional `δ_point′(v)` that is equivalent to `δ_point(-∇⊙v)`.

That being said, because the caller can always apply the derivatives to the test function instead of to the delta function (by definition of the distributional derivative), maybe this isn't strictly needed?

**Comment by santiagobadia** [comment]
Hi @stevengj 

As you say, the user can just use the definition of the distributional derivative, i.e., minus the derivative of the argument. Since this is straightforward in`Gridap`, I would not include derivatives of Dirac deltas.

As you say, this is not strictly needed, so I will close the issue.
