### ISSUE TITLE
Variable "order" overwritten in tutorial

### ISSUE THREAD

**Issue by eschnett** [gridap/Gridap.jl#521]
The tutorial on page <https://gridap.github.io/Tutorials/dev/pages/t002_validation/> defines a function `function run(n,order)`. The argument `order` is never used; it is overwritten by a statement `order = 1` further down. This seems wrong.

**Comment by eschnett** [comment]
The convergence test does not give the results described in the tutorial. The convergence orders are only circa 2 and 1, respectively.

**Comment by eschnett** [comment]
When I remove the spurious assignment in the function, both convergence orders are circa 3.

**Comment by santiagobadia** [comment]
Hi @eschnett ,

Yes, `order = 1` should be eliminated. Since you were running for linear elements, you did only observe 2,1 instead of (at least) the 3,2 expected for `order = 2`. When you have eliminated the `order = 1`, you observe 3,3. That is possible. You know that at least L2 error should decrease with slope -3 and H1 with -2. But you can observe more, due to some superconvergence property for the problem at hand.

**Comment by santiagobadia** [comment]
I have eliminated that line. I close the issue

**Comment by eschnett** [comment]
The tutorial text and the screen output still don't agree. I observe both convergence orders to be circa 3, different from what the tutorial text says.

**Comment by santiagobadia** [comment]
Yes, because for that, I had to change the plot (in fact, the previous plot agreed with the text). Now the plot has also been corrected.
