### ISSUE TITLE
Modules in test suite are expensive

### ISSUE THREAD

**Issue by eschnett** [gridap/Gridap.jl#548]
Gridap puts each test set into a module, and then uses `using` statements to make parts of Gridap available in that module. There are about 150 modules in the test suite.

A `using Gridap` statement takes on my laptop about 3.7 seconds (Julia 1.6). I think this setup might make the test suite much more expensive than it needs to be.

A module introduces a scope and thus separates the individual test suites. I think one could use another mechanism for that. I think the standard `@testset begin ... end` mechanism would already suffice for that.

Without modules, the `using Gridap.XXX` statements would be in the individual `runtests.jl` files in the subdirectories, each enabling one further part of Gridap and testing it.

**Comment by fverdugo** [comment]
Hi @eschnett

we like to enclose the test in modules so that each test has its own scope. The test suite is quite large, and having just a single scope will be difficult to maintain. 

Are the 3.7 seconds are for each instance of `using Gridap` appearing in the test suite or just for the first one ?

**Comment by eschnett** [comment]
I don't recall exactly what I measured. When I try to reproduce it now, the second and all following `using Gridap` statements are very cheap. I must have been confused.
