### ISSUE TITLE
Renaming Numa

### ISSUE THREAD

**Issue by fverdugo** [gridap/Gridap.jl#6]
Issue to find the final name for the project

**Comment by fverdugo** [comment]
@santiagobadia what about `Gridap` and `Gridap.jl` Grid-based approximation of PDEs in julia (www.gridap.org available)

`Grida.jl` (sounds better but has the same problems as numa)

**Comment by fverdugo** [comment]
EDIT: (www.grida.org is taken, but www.grida.io and others are free)

**Comment by fverdugo** [comment]
www.grida-jl.org is for 14$ at hover.com

**Comment by santiagobadia** [comment]
Grida is just grid + a, too exploited...
Gridap not excited, probably better Numap for the moment
The idea is only two syllables?

For archiving purposes:
I played with Numad, Numade, Numadic, etc, but somehow exploited
Numadig
NUMerical Approx of DIfferential equations with Grid-based method

**Comment by fverdugo** [comment]
2 Syllabes would be perfect like fempar, fenics ...

**Comment by fverdugo** [comment]
Grande.jl  hashashas

**Comment by santiagobadia** [comment]
I gibap (.jl) 😉

**Comment by santiagobadia** [comment]
Nudmag
Natmag (naturist magazine, nice pictures)

**Comment by fverdugo** [comment]
Gridify, gridea, grides

**Comment by santiagobadia** [comment]
gridade (sounds grid "aid")

**Comment by fverdugo** [comment]
what about Gridae?

**Comment by santiagobadia** [comment]
I think I have checked all GridXXX on the market...
Googling ```"gridae" cfd ```
There is a [CFD framework with AI called like this](https://books.google.es/books?id=0kkV91U84qsC&pg=PA55&lpg=PA55&dq=%22gridae%22+cfd&source=bl&ots=6ffGWevgrk&sig=ACfU3U3B_CbjKHJu5gEMuLxwd4r6mq0_tw&hl=en&sa=X&ved=2ahUKEwj7heOcvKrhAhVIxoUKHWNABocQ6AEwAHoECBMQAQ#v=onepage&q=%22gridae%22%20cfd&f=false)
See also [here](https://gridae.ceng.metu.edu.tr/)

How do we pronounce it in English? graidi, graidei,gridii..

We can probably keep Gridade and Gridae as final candidates

I think the first one is better because:
* It is not present on the Internet at all, 
* The English pronunciation is clear (thanks to Powerade et al)
* It is like "grid" "aid"
* Perfect acronym matching

With regard to Gridae:
* I like the latin plural declination
* But already a CFD AI package
* English pronunciation unclear, everyone is going to call it a different way

What is your list of pros / cons? 
After this, we can probably do a poll, with our list of pros/cons.
I think that the obvious English pronunciation and Internet presence is important.

**Comment by fverdugo** [comment]
Another variant: gridis

**Comment by fverdugo** [comment]
It seems that prefixes gridXxx NumXxx are very exploited. Perhaps we have to give a try and explore other ones, eg, based on approximation, discretization, solver, mesh, or whatever. Just a random thougt: apeqs (like apex). Not very exploited in the internet. Www.apeqs.org available

**Comment by santiagobadia** [comment]
I think that "grid" is the main difference with respect to what is already done in Julia.

Gridde (sunds like greedy)
Grid-based app of Dif Eq

Gridde and gridade are green fields on the internet

Griddeq, grideq...

**Comment by fverdugo** [comment]
Gridde perhaps my favorite so far

**Comment by fverdugo** [comment]
The double dd opens new possibilities, and can rescue some of the ones that we have discarded before because they are to exploited. Eg, griddea, gridda

Griddea (grid based diff eq approximation in julia) souns nice and it is a green field in the internet. Name available at github and griddea.org

**Comment by santiagobadia** [comment]
Griddea is ok, we can ask Jerrad how he would pronounce it in English

**Comment by santiagobadia** [comment]
I guess sthg like /griddiia/...
Seems to be non-used on the Internet

Habemus nomine?

**Comment by santiagobadia** [comment]
It seems gridea is not so much on the internet... so probably better

The gridea in github is not an organization, it is a repos. They can be repeated.

Even www.gridea.com free.

Gridea ok?

**Comment by fverdugo** [comment]
It can be a first candidate. But I would be open to better options until we release the project ( at latest when we write the paper)

**Comment by fverdugo** [comment]
Griddis seems also to be fresh snow in the internet. Griddis.com and griddis.org available. There is a github user with this name (0 stars) but one could use github.com/griddis-team/Griddis.jl
Or even github.com/lssc-team/Griddis.jl for the main repo.

The pro of this option is that it has a more obvious pronouciation than griddea. And that the spelling can be easilly inferred from the pronouncuation.

**Comment by santiagobadia** [comment]
Gridap... finally
