### ISSUE TITLE
Trace-based numerical methods (HDG, VEM, HHO...)

### ISSUE THREAD

**Issue by santiagobadia** [gridap/Gridap.jl#83]
We should be able to define spaces (of traces) on the mesh skeleton both continuous and discontinuous. With these spaces, we should be able to define hybridizable DG methods (HDG) but also other similar schemes as Hybridizable high order (HHO) schemes. With some extra work, we could also think about the implementation of Virtual Element methods (VEM).

**Comment by santiagobadia** [comment]
Hi @fverdugo 

Let me ellaborate more in this issue, since I think it is important (again, after talking to some people working on weak Galerkin, HHO, HDG, VEM).

I think we should be able to create hybrid spaces (traces on facets and cell-wise spaces). It will certainly imply global trace spaces like this...

```
skeleton_model = get_skeleton_model(model)

V = FESpace(
  reffe=:Lagrangian, order=order, valuetype=VectorValue{2,Float64},
  conformity=:H1, model=skeleton_model, dirichlet_tags=[5,6])
```

It is not so clear the type of conformity, probably we can also consider `C0` conformity... and we keep aside whether the solution belongs to `H^1/2_00(\Gamma)` or `H^1(\Gamma)`. We could also define `C0-tangent` and `C0-normal`... but this is another discussion.

I will write a HDG formulation as starting point, and see how we can implement it.

**Comment by fverdugo** [comment]
I have read a bit the reference about HDG, and I think that constructing the trace space is in fact the easy part. Building the local problems is another story. We will need some new data structures.

For HDG, since the traces are discontinuous you don't really need a model. In fact,  we can already construct the trace space (for the moment without Dirichlet BCs, including them is straight forward.) User API also to be improved...

```julia
using Gridap
using Gridap.ReferenceFEs
using Gridap.Geometry
using Gridap.FESpaces

domain = (0,1,0,1)
partition = (3,3)
model = CartesianDiscreteModel(domain,partition)

trian = Triangulation(ReferenceFE{1},model)

order = 3

reffes = [
  LagrangianRefFE(Float64,get_polytope(reffe),order)
  for reffe in get_reffes(trian)  ]

M = DiscontinuousFESpace(reffes,trian)

λh = FEFunction(M,rand(num_free_dofs(M)))

# in order to run this line I have had to fix a little bug. The patch will be in master soon.
writevtk(trian,"trian",nsubcells=30,cellfields=["trace"=>λh])
```
![trace](https://user-images.githubusercontent.com/48508177/75231561-f20f2f80-57b5-11ea-8e46-203c31c7b879.png)

I you want continuous traces, then you will need a model. However, I would not call it "skeleton model" since it also includes the boundary facets (up to now the skeleton refers to the interior facets only). I would call the constructor `TraceModel(model)` or implement a constructor that returns a model on any lower dim as follows `DiscreteModel(Polytope{1},model)`.

**Comment by fverdugo** [comment]
In PR #196: 

```julia
using Gridap

domain = (0,1,0,1)
partition = (3,3)
model = CartesianDiscreteModel(domain,partition)

model_1d = DiscreteModel(Polytope{1},model)

V = TestFESpace(
  model=model_1d,
  reffe=:Lagrangian,
  valuetype=Float64,
  order=3,
  conformity=:C0,
  dirichlet_tags="boundary")

u(x) = x[1]+x[2]

U = TrialFESpace(V,u)

uh = FEFunction(U,rand(num_free_dofs(U)))

trian_1d = Triangulation(model_1d)
writevtk(trian_1d,"trian_1d",nsubcells=30,cellfields=["uh"=>uh])
```

![cont_traces](https://user-images.githubusercontent.com/48508177/75441753-80beb080-595e-11ea-92b3-55d171c618d3.png)

**Comment by santiagobadia** [comment]
Great! One step closer to have advanced hybrid-based numerical methods.
Now, we have to think about the cell-wise local problems that couple the trace unknowns and the bulk unknowns, and how to integrate it with the global form for the traces.

**Comment by fverdugo** [comment]
We could even create models only for a sub-set edges, facets, etc, at the interface of several domains
