### ISSUE TITLE
confusion about vectors sizes

### ISSUE THREAD

**Issue by mahdimasmoudi** [gridap/Gridap.jl#973]
I am trying to undestand few steps from the code and I need help understanding how results are derived.

I start with 45 nodes of a simple cube.  I get 100 elements from this mesh.

A=get_matrix gives a 1785 x 1785 matrix
b=get_vector gives a 1785 elements vector. I suppose I am going to solve the system  AU=b where U is the displacement I am solving for.

The confusion comes out of the fact that U should have the dimension: number of nodes * number of DoFs which is 135 in this case and not 1785.

When I reach the last step to store the results in a vtk file it turns out that the vector stored is a 400 elements vector which is even more confusing.

I appreciate any help in this regard.

**Comment by JordiManyer** [comment]
@mahdimasmoudi I would probably need to see the code.

**Comment by JordiManyer** [comment]
Is the mesh composed of cubes or tetrahedra?

**Comment by JordiManyer** [comment]
Let's assume it's cubes, i.e you have `N_cells = 100` cuboid cells. 

In that case, each reference element has `N_nodes_x_element = (1+order)^D` nodes with `D` components each. In your particular case, 64 nodes and 192 dofs per cell. Some of them are indeed shared between cells (the ones in the nodes, edges and faces) but some of them are not (the interior ones). 

On top of this, you have dirichlet boundary conditions. That means that all dofs on the boundary will be eliminated and their contributions with go to your rhs. So those get subtracted from your total matrix size. 

When writing to vtk, you are not using the option to store higher-dimensional data. So your solution is interpolated back into first order. Probably the dirichlet dofs are added back, since VTK needs complete nodal data. 

So it's quite a bit more complicated than you think. If you want the simplest case, I would recommend first order 2D without any boundary conditions. You'll probably get easier counts.
